name: Setup Node.js versions

on:
  workflow_call:
    outputs:
      node-version:
        description: 'Common Node.js version'
        value: ${{ jobs.export.outputs.node-version }}
      npm-version:
        description: 'Common NPM version'
        value: ${{ jobs.export.outputs.npm-version }}

env:
  NODE_VERSION: 14
  NPM_VERSION: 9

jobs:
  export:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.setver.outputs.node_version }}
      npm-version: ${{ steps.setver.outputs.npm_version }}
    steps:
      - id: setver
        run: |
          echo "node_version=${{ env.NODE_VERSION }}" >> $GITHUB_OUTPUT
          echo "npm_version=${{ env.NPM_VERSION }}" >> $GITHUB_OUTPUT
