name: Publish package
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  get-vars:
    uses: ./.github/workflows/nodevars.yml

  main:
    needs: get-vars
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ needs.get-vars.outputs.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Setup npm
        run: npm i -g npm@${{ needs.get-vars.outputs.npm-version }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build-all
      - name: Publish
        run: npm publish --provenance
